'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class DescargueManual

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hfControlFiltroCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfControlFiltroCiudad As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cpValidacionYNotificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpValidacionYNotificacion As Global.EO.Web.CallbackPanel

    '''<summary>
    '''vuControlSesion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vuControlSesion As Global.NotusExpress.ValidacionURL

    '''<summary>
    '''epNotificador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents epNotificador As Global.NotusExpress.EncabezadoPagina

    '''<summary>
    '''cpGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpGeneral As Global.EO.Web.CallbackPanel

    '''<summary>
    '''pnlConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlConsulta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlConsultarPor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlConsultarPor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trPuntoVentaConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trPuntoVentaConsulta As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlPuntoVentaConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPuntoVentaConsulta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkPdvActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPdvActivo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trSerial As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtSerialConsultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSerialConsultar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''trFechaGestionConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trFechaGestionConsulta As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''dpFechaGestionInicialConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpFechaGestionInicialConsulta As Global.EO.Web.DatePicker

    '''<summary>
    '''dpFechaGestionFinalConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpFechaGestionFinalConsulta As Global.EO.Web.DatePicker

    '''<summary>
    '''trTipoProductoConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTipoProductoConsulta As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlTipoProductoConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoProductoConsulta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trConsultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trConsultar As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbConsultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbConsultar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''imgLoading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLoading As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlGestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGestion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tsInfoGestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tsInfoGestion As Global.EO.Web.TabStrip

    '''<summary>
    '''mpInfoGestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpInfoGestion As Global.EO.Web.MultiPage

    '''<summary>
    '''pvDatosCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvDatosCliente As Global.EO.Web.PageView

    '''<summary>
    '''pnlInfoVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfoVenta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cpInfoVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpInfoVenta As Global.EO.Web.CallbackPanel

    '''<summary>
    '''dpFechaVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpFechaVenta As Global.EO.Web.DatePicker

    '''<summary>
    '''rfvFechaVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvFechaVenta As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtAtendidoPor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAtendidoPor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revAtendidoPor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revAtendidoPor As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvAtendidoPor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAtendidoPor As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtNumIdOperadorCallCenter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumIdOperadorCallCenter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revNumIdOperadorCall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revNumIdOperadorCall As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtNumPlanillaPreAnalisis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumPlanillaPreAnalisis As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revNumPlanillaPreAnalisis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revNumPlanillaPreAnalisis As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvNumPlanillaPreAnalisis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumPlanillaPreAnalisis As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtNumVentaPlanilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumVentaPlanilla As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revNumVentaPlanilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revNumVentaPlanilla As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvNumVentaPlanilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumVentaPlanilla As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlResultadoConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlResultadoConsulta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvResultadoConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvResultadoConsulta As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlTipoProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoProducto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvTipoProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTipoProducto As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''trInfoProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trInfoProducto As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlProductoPadre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductoPadre As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvTipoDeTarjetaRequerido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTipoDeTarjetaRequerido As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlSubproducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSubproducto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvProducto As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''trInfoSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trInfoSerial As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtNumPagare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumPagare As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revNumPagare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revNumPagare As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvNumPagare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumPagare As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtSerialTarjeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSerialTarjeta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvSerialTarjeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSerialTarjeta As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revSerialTarjeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revSerialTarjeta As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtObservacionOperadorCall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacionOperadorCall As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkNovedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNovedad As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trDetalleNovedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDetalleNovedad As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''gvNovedades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvNovedades As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''trAcciones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAcciones As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAccion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''trBotonAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trBotonAccion As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbContinuar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbContinuar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''trTraslados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trTraslados As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtSerialTrasladar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSerialTrasladar As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBodegaOrigen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBodegaOrigen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlBodegaDestino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBodegaDestino As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbTrasladarSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTrasladarSerial As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbCancelarVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCancelarVenta As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbDestruir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDestruir As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbTrasladar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbTrasladar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbFaltante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbFaltante As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbLiberar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLiberar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlHistoricoVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHistoricoVenta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cpHistoricoVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpHistoricoVenta As Global.EO.Web.CallbackPanel

    '''<summary>
    '''gvHistoricoVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvHistoricoVenta As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''cpMensajeConfirmacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpMensajeConfirmacion As Global.EO.Web.CallbackPanel

    '''<summary>
    '''dlgMensajeReferido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlgMensajeReferido As Global.EO.Web.Dialog

    '''<summary>
    '''lblRegistroOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegistroOk As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSolicitudReferido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSolicitudReferido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSi As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ldrWait control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ldrWait As Global.NotusExpress.Loader

    '''<summary>
    '''lblTipoConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoConsulta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTransaccionID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransaccionID As Global.System.Web.UI.WebControls.Label
End Class
