'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GestionDeVenta

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hfControlFiltroCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfControlFiltroCiudad As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cpValidacionYNotificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpValidacionYNotificacion As Global.EO.Web.CallbackPanel

    '''<summary>
    '''vuControlSesion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vuControlSesion As Global.NotusExpress.ValidacionURL

    '''<summary>
    '''epNotificador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents epNotificador As Global.NotusExpress.EncabezadoPagina

    '''<summary>
    '''cpGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpGeneral As Global.EO.Web.CallbackPanel

    '''<summary>
    '''pnlConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlConsulta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtIdentificacionConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdentificacionConsulta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvIdentificacionConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvIdentificacionConsulta As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtTransaccionConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransaccionConsulta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvTransaccionConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTransaccionConsulta As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''lbConsultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbConsultar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''imgLoading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLoading As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlGestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGestion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tsInfoGestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tsInfoGestion As Global.EO.Web.TabStrip

    '''<summary>
    '''mpInfoGestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpInfoGestion As Global.EO.Web.MultiPage

    '''<summary>
    '''pvDatosCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvDatosCliente As Global.EO.Web.PageView

    '''<summary>
    '''pnlInfoOrigenGestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfoOrigenGestion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cpPDV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpPDV As Global.EO.Web.CallbackPanel

    '''<summary>
    '''ddlPdv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPdv As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkPdvActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPdvActivo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rfvPdv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvPdv As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cpAsesorComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpAsesorComercial As Global.EO.Web.CallbackPanel

    '''<summary>
    '''ddlAsesorComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAsesorComercial As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''chkAsesorActivo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAsesorActivo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''rfvAsesorComercial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAsesorComercial As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''pnlDatosPersonales control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlDatosPersonales As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''ddlTipoIdentificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoIdentificacion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvTipoIdentificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTipoIdentificacion As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtIdentificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIdentificacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revIdentificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revIdentificacion As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvIdentificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvIdentificacion As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtNombreApellido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombreApellido As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revNombreApellido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revNombreApellido As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvNombreApellido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNombreApellido As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtFiltroCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFiltroCiudad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cpCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpCiudad As Global.EO.Web.CallbackPanel

    '''<summary>
    '''ddlCiudadResidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCiudadResidencia As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblNumCiudades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblNumCiudades As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rfvCiudadResidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvCiudadResidencia As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtDireccionResidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDireccionResidencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revDireccionResidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revDireccionResidencia As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvDireccionResidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvDireccionResidencia As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtBarrioResidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBarrioResidencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revBarrioResidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revBarrioResidencia As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvBarrio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvBarrio As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtTelefonoResidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelefonoResidencia As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revtTelefonoResidencia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revtTelefonoResidencia As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtCelular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCelular As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revCelular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revCelular As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtDireccionOficina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDireccionOficina As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revDireccionOficina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revDireccionOficina As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtTelefonoOficina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTelefonoOficina As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revTelefonoOficina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revTelefonoOficina As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIngreso As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revIngreso As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvIngreso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvIngreso As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlEstatusLaboral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlEstatusLaboral As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvEstatusLaboral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvEstatusLaboral As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEmail As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revEmail As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''trInfoPreventa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trInfoPreventa As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''pnlRegistroPreventa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlRegistroPreventa As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cusDatosMinimos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusDatosMinimos As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lblRegistrarPreventa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegistrarPreventa As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCancelar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlInfoVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlInfoVenta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cpInfoVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpInfoVenta As Global.EO.Web.CallbackPanel

    '''<summary>
    '''dpFechaVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dpFechaVenta As Global.EO.Web.DatePicker

    '''<summary>
    '''rfvFechaVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvFechaVenta As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtAtendidoPor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAtendidoPor As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revAtendidoPor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revAtendidoPor As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvAtendidoPor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvAtendidoPor As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtNumIdOperadorCallCenter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumIdOperadorCallCenter As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revNumIdOperadorCall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revNumIdOperadorCall As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtNumPlanillaPreAnalisis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumPlanillaPreAnalisis As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revNumPlanillaPreAnalisis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revNumPlanillaPreAnalisis As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvNumPlanillaPreAnalisis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumPlanillaPreAnalisis As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtNumVentaPlanilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumVentaPlanilla As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revNumVentaPlanilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revNumVentaPlanilla As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvNumVentaPlanilla control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumVentaPlanilla As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlResultadoConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlResultadoConsulta As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvResultadoConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvResultadoConsulta As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlTipoProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoProducto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvTipoProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTipoProducto As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''trInfoProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trInfoProducto As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlProductoPadre control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlProductoPadre As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvTipoDeTarjetaRequerido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvTipoDeTarjetaRequerido As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''ddlSubproducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSubproducto As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rfvProducto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvProducto As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''trInfoSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trInfoSerial As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtNumPagare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumPagare As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''revNumPagare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revNumPagare As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''rfvNumPagare control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumPagare As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txtSerialTarjeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSerialTarjeta As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvSerialTarjeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvSerialTarjeta As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revSerialTarjeta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revSerialTarjeta As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''txtObservacionOperadorCall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacionOperadorCall As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''chkNovedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkNovedad As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''trInfoNovedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trInfoNovedad As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''ddlTipoNovedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlTipoNovedad As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtObservacionesNovedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacionesNovedad As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvObservacionesNovedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvObservacionesNovedad As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''trAccionesNovedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trAccionesNovedad As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbRegistrarNovedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRegistrarNovedad As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''trDetalleNovedad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trDetalleNovedad As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''gvNovedades control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvNovedades As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbRegistrarVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRegistrarVenta As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbCancelarVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCancelarVenta As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''pnlHistoricoVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlHistoricoVenta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cpHistoricoVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpHistoricoVenta As Global.EO.Web.CallbackPanel

    '''<summary>
    '''gvHistoricoVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvHistoricoVenta As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbCancelarHistorico control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCancelarHistorico As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbNuevaVenta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbNuevaVenta As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cpMensajeConfirmacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpMensajeConfirmacion As Global.EO.Web.CallbackPanel

    '''<summary>
    '''dlgMensajeReferido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlgMensajeReferido As Global.EO.Web.Dialog

    '''<summary>
    '''lblRegistroOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegistroOk As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSolicitudReferido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSolicitudReferido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSi As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ldrWait control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ldrWait As Global.NotusExpress.Loader

    '''<summary>
    '''lblTipoConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoConsulta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExisteTransaccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExisteTransaccion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTransaccionExistente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransaccionExistente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEsNueva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEsNueva As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIdentificacionAnterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdentificacionAnterior As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTieneVentas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTieneVentas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIdClienteOriginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdClienteOriginal As Global.System.Web.UI.WebControls.Label
End Class
