'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class RegistrarTarjetaDestruido

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hfControlFiltroCiudad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfControlFiltroCiudad As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''cpValidacionYNotificacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpValidacionYNotificacion As Global.EO.Web.CallbackPanel

    '''<summary>
    '''vuControlSesion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vuControlSesion As Global.NotusExpress.ValidacionURL

    '''<summary>
    '''epNotificador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents epNotificador As Global.NotusExpress.EncabezadoPagina

    '''<summary>
    '''cpGeneral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpGeneral As Global.EO.Web.CallbackPanel

    '''<summary>
    '''pnlConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlConsulta As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''txtNumeroSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumeroSerial As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rfvNumeroSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rfvNumeroSerial As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''revNumeroSerial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents revNumeroSerial As Global.System.Web.UI.WebControls.RegularExpressionValidator

    '''<summary>
    '''lbAgregar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbAgregar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''imgLoading control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgLoading As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''pnlGestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlGestion As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''tsInfoGestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tsInfoGestion As Global.EO.Web.TabStrip

    '''<summary>
    '''mpInfoGestion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mpInfoGestion As Global.EO.Web.MultiPage

    '''<summary>
    '''pvDatosCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pvDatosCliente As Global.EO.Web.PageView

    '''<summary>
    '''pnlVentasDestruir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlVentasDestruir As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''cpVentasDestruir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpVentasDestruir As Global.EO.Web.CallbackPanel

    '''<summary>
    '''gvVentasDestruir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvVentasDestruir As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''lbCancelar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbCancelar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbContinuar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbContinuar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''tblMotivoDestruccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblMotivoDestruccion As Global.System.Web.UI.HtmlControls.HtmlTable

    '''<summary>
    '''trObservacionDestruccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trObservacionDestruccion As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''txtObservacionDestruccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObservacionDestruccion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''tr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tr1 As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lbDestruir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbDestruir As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cpMensajeConfirmacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpMensajeConfirmacion As Global.EO.Web.CallbackPanel

    '''<summary>
    '''dlgMensajeReferido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dlgMensajeReferido As Global.EO.Web.Dialog

    '''<summary>
    '''lblRegistroOk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegistroOk As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSolicitudReferido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSolicitudReferido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSi As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNo As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''ldrWait control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ldrWait As Global.NotusExpress.Loader

    '''<summary>
    '''lblTipoConsulta control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTipoConsulta As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblExisteTransaccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExisteTransaccion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTransaccionExistente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransaccionExistente As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblEsNueva control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEsNueva As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIdentificacionAnterior control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdentificacionAnterior As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTieneVentas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTieneVentas As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblIdClienteOriginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIdClienteOriginal As Global.System.Web.UI.WebControls.Label
End Class
