'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SelectorDireccion

    '''<summary>
    '''memoDireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents memoDireccion As Global.DevExpress.Web.ASPxMemo

    '''<summary>
    '''hlHome control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hlHome As Global.DevExpress.Web.ASPxHyperLink

    '''<summary>
    '''hdDireccionEdicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdDireccionEdicion As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''pcDireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcDireccion As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''pcContentContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcContentContenido As Global.DevExpress.Web.PopupControlContentControl

    '''<summary>
    '''lblDireccionOriginal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDireccionOriginal As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''rpDireccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpDireccion As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''PanelContent2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent2 As Global.DevExpress.Web.PanelContent

    '''<summary>
    '''cmbNombreVia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbNombreVia As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''spNumeroVia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spNumeroVia As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''cmbLetraVia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLetraVia As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmbBisVia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBisVia As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmbOrientacionVia control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbOrientacionVia As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''spNumeroViaSec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spNumeroViaSec As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''cmbLetraViaSec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLetraViaSec As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''cmbBisViaSec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBisViaSec As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''spNumeroNomenclatura control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spNumeroNomenclatura As Global.DevExpress.Web.ASPxSpinEdit

    '''<summary>
    '''cmbOrientacionViaSec control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbOrientacionViaSec As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''divAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divAdicional As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cpnl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpnl As Global.DevExpress.Web.ASPxCallbackPanel

    '''<summary>
    '''PanelContent5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent5 As Global.DevExpress.Web.PanelContent

    '''<summary>
    '''rpAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpAdicional As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''PanelContent1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PanelContent1 As Global.DevExpress.Web.PanelContent

    '''<summary>
    '''cmbDatosAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDatosAdicional As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''txtTextoAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTextoAdicional As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''lblComentario control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComentario As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txtAdicional control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdicional As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''mmDireccionTmp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents mmDireccionTmp As Global.DevExpress.Web.ASPxMemo
End Class
