'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LoginLm

    '''<summary>
    '''lblCambioConfirmacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCambioConfirmacion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''rpPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rpPrincipal As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''lgAutenticador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lgAutenticador As Global.System.Web.UI.WebControls.Login

    '''<summary>
    '''lbRecuperarContrasena control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbRecuperarContrasena As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''PopCambioDeContrasenaIngresoPrimeraVez control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopCambioDeContrasenaIngresoPrimeraVez As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''RpCambioDeContrasenaIngresoPrimeraVez control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RpCambioDeContrasenaIngresoPrimeraVez As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''CambioContrasena control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CambioContrasena As Global.System.Web.UI.WebControls.ChangePassword

    '''<summary>
    '''lblMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''PopRecuperarContrasena control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PopRecuperarContrasena As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''RpRecuperarContrasena control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RpRecuperarContrasena As Global.DevExpress.Web.ASPxRoundPanel

    '''<summary>
    '''recuperarContrasena control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents recuperarContrasena As Global.System.Web.UI.WebControls.PasswordRecovery

    '''<summary>
    '''pcCaptcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pcCaptcha As Global.DevExpress.Web.ASPxPopupControl

    '''<summary>
    '''captcha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents captcha As Global.DevExpress.Web.ASPxCaptcha

    '''<summary>
    '''btnConfirmar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnConfirmar As Global.DevExpress.Web.ASPxButton
End Class
