'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class BuscarGestionDeVenta

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''cpEncabezado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpEncabezado As Global.EO.Web.CallbackPanel

    '''<summary>
    '''vuControlSesion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents vuControlSesion As Global.NotusExpress.ValidacionURL

    '''<summary>
    '''epNotificador control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents epNotificador As Global.NotusExpress.EncabezadoPagina

    '''<summary>
    '''cpFiltrosBusqueda control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpFiltrosBusqueda As Global.EO.Web.CallbackPanel

    '''<summary>
    '''imgSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgSearch As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''ddlPdv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPdv As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlAsesor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlAsesor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtNumIdCliente control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNumIdCliente As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlResultadoProceso control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlResultadoProceso As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtFechaInicial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaInicial As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''txtFechaFinal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFechaFinal As Global.System.Web.UI.HtmlControls.HtmlInputText

    '''<summary>
    '''rblTipoFecha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rblTipoFecha As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''cusSeleccionFiltro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cusSeleccionFiltro As Global.System.Web.UI.WebControls.CustomValidator

    '''<summary>
    '''lbConsultar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbConsultar As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''lbLimpiarFiltros control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbLimpiarFiltros As Global.System.Web.UI.WebControls.LinkButton

    '''<summary>
    '''cpResultado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cpResultado As Global.EO.Web.CallbackPanel

    '''<summary>
    '''gvResultado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvResultado As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''ldrWait control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ldrWait As Global.NotusExpress.Loader
End Class
